/******************* Generated by UpShift Transformer Logic *******************/
package org.integrallis;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import java.util.Arrays;
import javax.servlet.Filter;
import org.springframework.boot.web.servlet.FilterRegistrationBean;
import com.opensymphony.module.sitemesh.filter.PageFilter;
import org.apache.struts2.dispatcher.FilterDispatcher;
import org.apache.struts2.dispatcher.ActionContextCleanUp;

@Configuration()
public class FilterBeanConfiguration {

    @Bean()
    public FilterRegistrationBean sitemesh() {
        return buildFilterRegistration(1, new PageFilter(), "/*");
    }

    @Bean()
    public FilterRegistrationBean action2() {
        return buildFilterRegistration(1, new FilterDispatcher(), "/*");
    }

    @Bean()
    public FilterRegistrationBean action2-cleanup() {
        return buildFilterRegistration(1, new ActionContextCleanUp(), "/*");
    }

    private FilterRegistrationBean buildFilterRegistration(int order, Filter filter, String... urlPatterns) {
        FilterRegistrationBean registration = new FilterRegistrationBean();
        registration.setFilter(filter);
        registration.setUrlPatterns(Arrays.asList(urlPatterns));
        registration.setOrder(order);
        return registration;
    }
}
