/******************* Generated by UpShift Transformer Logic *******************/
package org.integrallis;

import org.springframework.context.annotation.Configuration;
import java.util.Arrays;
import javax.servlet.Servlet;
import org.springframework.context.annotation.Bean;
import org.springframework.boot.web.servlet.ServletRegistrationBean;
import org.apache.struts2.views.JspSupportServlet;
import uk.ltd.getahead.dwr.DWRServlet;

@Configuration()
public class ServletBeanConfiguration {

    @Bean()
    public ServletRegistrationBean jspsupportservlet() {
        return buildServletRegistration(5, new JspSupportServlet(), "/*");
    }

    @Bean()
    public ServletRegistrationBean dwr() {
        return buildServletRegistration(0, new DWRServlet(), "/dwr/*");
    }

    private ServletRegistrationBean buildServletRegistration(int loadOnStartup, Servlet servlet, String... urlPatterns) {
        ServletRegistrationBean registration = new ServletRegistrationBean();
        registration.setServlet(servlet);
        registration.setUrlMappings(Arrays.asList(urlPatterns));
        registration.setLoadOnStartup(loadOnStartup);
        return registration;
    }
}
